/*
(C) copyright 2018 Silviu Ilinescu
All rights reserved

 */
package com.siit.bubblesortalgorithm;

import static com.siit.bubblesortalgorithm.PrintingArray.loopingTheArrayAndPrinting;

/**
 * The BubbleSortApp class implements an application that prints a given array of
 * SalesRepresentative objects, then sorts the array in descending order and prints the sorted array.
 * The sorting is done based on the amount of revenue generated by each object.
 * Each rep has a number of sales and a quota/sale.
 *
 *Created 22-May-2018
 * @author Silviu_Ilinescu
 */

public class BubbleSortApp {

    /**
     * This is the main method which makes use of bubbleSort method in class SortAlgorithm
     * and instances from class SalesRep
     *
     * @param args Unused
     */

    public static void main(String[] args) {

        SalesRep[] reps = {new SalesRep("John", 4, 100),
                new SalesRep("Dany", 10, 250),
                new SalesRep("Alicia", 5, 150),
                new SalesRep("Mary", 7, 200)};


        System.out.println("Array before bubble sort:");
        loopingTheArrayAndPrinting(reps); //not instantiated because static

        System.out.println();
        System.out.println();

        SortAlgorithm sort = new SortAlgorithm();  // instantiated
        sort.bubbleSort(reps);

        System.out.println("Array after bubble sorting by biggest salesWorth: ");
        loopingTheArrayAndPrinting(reps);

    }
}



